# Generated by Django 5.0.1 on 2024-01-27 17:42

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='District Name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='District Name')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='District Name')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Quarter Name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Quarter Name')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Quarter Name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='common.district', verbose_name='District')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Region Name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Region Name')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Region Name')),
            ],
            options={
                'db_table': 'regions',
                'indexes': [models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_uz'), descending=True), name='region_name_uz_upper_index'), models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_ru'), descending=True), name='region_name_ru_upper_index')],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='common.region', verbose_name='Region'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_uz'), descending=True), name='district_name_uz_upper_index'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_ru'), descending=True), name='district_name_ru_upper_index'),
        ),
    ]
