# Generated by Django 5.0.1 on 2024-01-27 08:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='district',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_uz'), descending=True), name='district_name_uz_upper_index'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_ru'), descending=True), name='district_name_ru_upper_index'),
        ),
        migrations.AddIndex(
            model_name='quarter',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_uz'), descending=True), name='quarter_name_uz_upper_index'),
        ),
        migrations.AddIndex(
            model_name='quarter',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_ru'), descending=True), name='quarter_name_ru_upper_index'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_uz'), descending=True), name='region_name_uz_upper_index'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Upper('name_ru'), descending=True), name='region_name_ru_upper_index'),
        ),
    ]
